repos:
- repo: local
  hooks:
  - id: v-fmt
    name: coding style
    entry: v fmt -verify .
    language: system
    files: \.v$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    files: \.(yaml|yml)$
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
  - id: forbid-binary
